### ISSUE TITLE
ipset: not found

### ISSUE THREAD

**Issue by asmh1989** [guolinke/ac86u-hacks#5]
```
admin@RT-AC86U:/jffs/ss# ./start_ss.sh
./start_ss.sh: line 33: ipset: not found
```
http://pkg.entware.net/binaries/armv7/Packages.html
这里搜索了下, 有ipset4, 装了后

```
admin@RT-AC86U:/jffs/ss# ./start_ss.sh
ipset v4.5: Unknown arg `-!'
Try `ipset -H' or 'ipset --help' for more information.
```

不知道, 你用的是哪个版本 @guolinke

**Comment by guolinke** [comment]
@asmh1989 那个ipset是用来测试新的merlin固件的，不过好像现在merlin还是不支持ipset，系统记录里面一堆错误。
现在master 分支的代码回滚了，不需要ipset
